"""add article visibility and comments flags

Revision ID: eefbf75b5317
Revises: bbdee0caec4f
Create Date: 2026-03-04 23:20:15.715067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eefbf75b5317'
down_revision = 'bbdee0caec4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_comments', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('is_public')
        batch_op.drop_column('allow_comments')

    # ### end Alembic commands ###
